# Generated by Django 4.2.6 on 2023-10-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_myclubuser_venue_event_attendees_alter_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attendee', to='events.myclubuser'),
        ),
    ]
